### ISSUE TITLE
Reading coverage values

### ISSUE THREAD

**Issue by vkodimut** [simplecov-ruby/simplecov#971]
Hello Team,
Question on reading the coverall results. Is there a way I can read the total covered %, relevant lines, lines covered, lines missed etc  which appears in index.html. I would like to gather these high level result over time.
Is it possible to read from `Simplecov::Result`  ? Please suggest.

Thanks!

**Comment by vkodimut** [comment]
Any suggestions @PragTob

**Comment by colszowka** [comment]
@vkodimut while i understand this issue seems be of big importance to you please refrain from pinging specific volunteers working for free on this project in their spare time, especially repinging a mere couple of hours after opening a support ticket on the issue. This kind of behaviour is what contributes to maintainers of open source projects to burn out and leave the space, leaving all of us worse off.

What you are looking for is likely a custom formatter, please read the readme regarding that topic. There is also a list of existing 3rd party formatters which you can use as a starting point.

**Comment by vkodimut** [comment]
Sorry about that @colszowka  .. I will look into custom formatter.. BTW it was over 12hrs after opening ticket..

**Comment by colszowka** [comment]
@vkodimut many paid services will have you wait longer on a support ticket. This is a volunteer-driven open source software project, please align your expectations accordingly. This kind of behaviour just leads to unnecessary stress on people trying to do good for the community. Thanks!

**Comment by PragTob** [comment]
First thanks @colszowka 💚 

@vkodimut Christoph is (naturally) exactly right, you're probably looking for a custom formatter - maybe a custom `at_exit` behaviour could also help you. You can have access to `SimpleCov::Result` in both cases and `#coverage_statistics` has all the information there.

**Comment by vkodimut** [comment]
Thanks @PragTob  yes, I figured that out after closer look at `SimpleCov::Result` .. Sorry for all the noise !!
